package com.beyondh.dataprovider;

import com.beyondh.cases.bill.BillCases;
import com.beyondh.constants.CreditConstants;
import com.beyondh.constants.DebitConstants;
import com.beyondh.constants.TestConstants;
import com.beyondh.enums.pms.BillItemType;
import com.beyondh.invoker.OrderAPIInvoker;
import com.beyondh.model.bill.*;
import com.beyondh.model.order.CheckinInfo;
import com.beyondh.model.order.OrderInfo;
import com.beyondh.utility.ClientGroup;
import com.beyondh.utility.Helper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestContext;
import org.testng.ITestContext;
import org.testng.annotations.DataProvider;

import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Random;

@ClientGroup(TestConstants.GRPOUP_BILL)
public class BillDataProvider extends  AbstractTestDataProvider {

    protected  static HashMap<String,String> _billData = _data.get(TestConstants.DATA_MODULE_BILL);

    public static final String DATA_GETBILLBALANCE = "GetBillBalance";


    public static final String DATA_ADDBILLITEMS = "addBillItem";

    public static final String DATA_ONLINEPAYMENT = "OnlinePaymentCase";

    public static final String DATA_GENERATEADDITIONALROOMRENT = "GenerateAdditionalRoomRentCase";

    @DataProvider(name = DATA_GETBILLBALANCE)
    public static Object[][] getBillBalanceData(ITestContext context) {

        CheckinInfo check = getDefaultCheckIn(context);
        return new Object[][]{
                {new BillBalanceGetModel(check.getBillId(),getOrgId(),false)},
                {new BillBalanceGetModel(check.getBillId(),getOrgId(),true)}
        };
    }

    @DataProvider(name = DATA_ADDBILLITEMS)
    public static Object[][] addBillItemData(ITestContext context) {

        BigDecimal rmbAmount =  Helper.NextDouble(100);
        BigDecimal bankAmount =  Helper.NextDouble(100);
        BigDecimal memberAmount =  Helper.NextDouble(100);
        BigDecimal rmbReturnAmount =  Helper.NextDouble(100);

        BigDecimal debit1001Amount =  Helper.NextDouble(100);
        BigDecimal debit1003Amount =  Helper.NextDouble(100);
        BigDecimal debit2000Amount =  Helper.NextDouble(100);
        BigDecimal debit4000Amount =  Helper.NextDouble(100);
        BigDecimal debit5000Amount =  Helper.NextDouble(100);
        BigDecimal debit6000Amount =  Helper.NextDouble(100);
        BigDecimal debit6500Amount =  Helper.NextDouble(100);
        BigDecimal debit7500Amount =  Helper.NextDouble(100);
        BigDecimal debit6110Amount =  Helper.NextDouble(100);
        BigDecimal debit8000Amount =  Helper.NextDouble(100);

        OrderInfo order = getDefaultOrder(context);
        CheckinInfo check = getDefaultCheckIn(context);
        return   new Object[][]{
                //接待单付款科目
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9110,
                        rmbAmount,
                        "generated by case add RMB bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9120,
                        bankAmount,
                        "generated by case add bank bill",
                        new PaymentModel(_billData.get("BankKey"),_billData.get("BankCardNumber"),bankAmount))
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9130,
                        memberAmount,
                        "generated by case add member bill",
                        new PaymentModel(memberAmount,_commonData.get("MemberId")))
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9111,
                        rmbReturnAmount,
                        "generated by case add RMB return bill")
                },
                //接待单消费科目
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D1001,
                        debit1001Amount,
                        "generated by case add d1001 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D1003,
                        debit1003Amount,
                        "generated by case add d1003 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D2000,
                        debit2000Amount,
                        "generated by case add d2000 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D4000,
                        debit4000Amount,
                        "generated by case add d4000 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D5000,
                        debit5000Amount,
                        "generated by case add d5000 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6000,
                        debit6000Amount,
                        "generated by case add d6000 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6500,
                        debit6500Amount,
                        "generated by case add d6500 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D7500,
                        debit7500Amount,
                        "generated by case add d7500 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6110,
                        debit6110Amount,
                        "generated by case add d6110 bill")
                },
                {new BillItemAddModel(getOrgId(),check.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D8000,
                        debit8000Amount,
                        "generated by case add d8000 bill")
                },
                //预定单付款科目
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9110,
                        rmbAmount,
                        "generated by case add RMB bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9120,
                        bankAmount,
                        "generated by case add bank bill",
                        new PaymentModel(_billData.get("BankKey"),_billData.get("BankCardNumber"),bankAmount))
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9130,
                        memberAmount,
                        "generated by case add member bill",
                        new PaymentModel(memberAmount,_commonData.get("MemberId")))
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Credit.getStringValue(),
                        CreditConstants.CREDIT_C9111,
                        rmbReturnAmount,
                        "generated by case add RMB return bill")
                },
                //预定单消费科目
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D1001,
                        debit1001Amount,
                        "generated by case add d1001 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D1003,
                        debit1003Amount,
                        "generated by case add d1003 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D2000,
                        debit2000Amount,
                        "generated by case add d2000 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D4000,
                        debit4000Amount,
                        "generated by case add d4000 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D5000,
                        debit5000Amount,
                        "generated by case add d5000 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6000,
                        debit6000Amount,
                        "generated by case add d6000 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6500,
                        debit6500Amount,
                        "generated by case add d6500 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D7500,
                        debit7500Amount,
                        "generated by case add d7500 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D6110,
                        debit6110Amount,
                        "generated by case add d6110 bill")
                },
                {new BillItemAddModel(getOrgId(),order.getBillId(),
                        BillItemType.Debit.getStringValue(),
                        DebitConstants.DEBIT_D8000,
                        debit8000Amount,
                        "generated by case add d8000 bill")
                },
        };
    }

    @DataProvider(name = DATA_ONLINEPAYMENT)
    public static Object[][] onlinePaymentCaseData(ITestContext context) {

        CheckinInfo check = getDefaultCheckIn(context);
        return new Object[][]{
                {new OnlinePaymentAddModel(getOrgId(),check.getBillId(),String.format("%s - %s",check.getRoomNumber(),check.getCheckinCustomer().getName()),_billData.get("OnlinePay"),Helper.NextDouble(100)),_commonData.get("WeChatBankType")}
        };
    }

    @DataProvider(name = DATA_GENERATEADDITIONALROOMRENT)
    public static Object[][] generateAdditionalRoomRentCaseData(ITestContext context) {

        CheckinInfo check = getDefaultCheckIn(context);
        return new Object[][]{
                {new AdditionalRoomRentGenerateModel(getOrgId(),new AdditionalDetailRoomRentGenerateModel[]{new AdditionalDetailRoomRentGenerateModel(check.getOccupationId())})}
        };
    }
}

